# FacturApp avec Docker
version: '3.8'

services:
  # MongoDB
  mongodb:
    image: mongo:6.0
    restart: unless-stopped
    environment:
      MONGO_INITDB_DATABASE: billing_app
    volumes:
      - mongodb_data:/data/db
      - ./database_export:/docker-entrypoint-initdb.d
    ports:
      - "27017:27017"
    networks:
      - facturapp-network

  # Backend FastAPI
  backend:
    build: ./backend
    restart: unless-stopped
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - SECRET_KEY=${SECRET_KEY}
      - ALGORITHM=HS256
      - ACCESS_TOKEN_EXPIRE_MINUTES=30
    ports:
      - "8001:8001"
    networks:
      - facturapp-network
    volumes:
      - ./backend:/app
    command: uvicorn server:app --host 0.0.0.0 --port 8001 --reload

  # Frontend React
  frontend:
    build: ./frontend
    restart: unless-stopped
    depends_on:
      - backend
    environment:
      - REACT_APP_BACKEND_URL=http://localhost:8001
    ports:
      - "3000:3000"
    networks:
      - facturapp-network
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: npm start

  # Nginx Reverse Proxy (pour production)
  nginx:
    image: nginx:alpine
    restart: unless-stopped
    depends_on:
      - frontend
      - backend
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/ssl
    networks:
      - facturapp-network

volumes:
  mongodb_data:

networks:
  facturapp-network:
    driver: bridge